[env:ttgo-t-beam]
platform = espressif32
board = ttgo-t-beam
framework = arduino

monitor_speed = 115200
upload_speed = 921600

lib_deps =
    thingpulse/ESP8266 and ESP32 OLED driver for SSD1306 displays@^4.6.1
    lewisxhe/XPowersLib